/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import com.Product.form.SanPhamForm;
import javax.swing.JOptionPane;
import main.entity.SanPham;
import main.repository.SanPhamRepository;

/**
 *
 * @author ADMIN
 */
public class SuaSanPhamJFrame extends javax.swing.JFrame {

    private SanPhamRepository repo = new SanPhamRepository();
    String id_sp = SanPhamForm.ma_sanpham;

    /**
     * Creates new form SuaSanPhamJFrame
     */
    public SuaSanPhamJFrame() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    private SanPham getFormData() {
        // Kiểm tra tên sản phẩm
        String tenSanPham = txt_TenSanPham.getText().trim();
        String moTaSanPham = txt_MoTaSanPham.getText().trim();
        tenSanPham = tenSanPham.split(" ")[0];
        moTaSanPham = moTaSanPham.split(" ")[0];

        if (tenSanPham.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên sản phẩm", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (tenSanPham.length() > 20) {
            JOptionPane.showMessageDialog(null, "Tên sản phẩm không được vượt quá 20 ký tự", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (!tenSanPham.matches("^[\\p{L}\\s]+$")) {
            JOptionPane.showMessageDialog(null, "Tên sản phẩm không được chứa ký tự đặc biệt hoặc số", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        // Cắt chuỗi tên sản phẩm nếu cần thiết (đảm bảo không vượt quá 20 ký tự)
        if (tenSanPham.length() > 20) {
            tenSanPham = tenSanPham.substring(0, 20);
        }

        if (moTaSanPham.length() > 30) {
            JOptionPane.showMessageDialog(null, "Mô tả sản phẩm không được vượt quá 30 ký tự", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            moTaSanPham = moTaSanPham.substring(0, 30);
        }

        SanPham sp = SanPham.builder()
                .maSanPham(txt_MaSanPham.getText())
                .tenSanPham(txt_TenSanPham.getText())
                .moTa(txt_MoTaSanPham.getText())
                .build();

        return sp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_MaSanPham = new com.Product.GUI.textfield.TextField();
        txt_TenSanPham = new com.Product.GUI.textfield.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_MoTaSanPham = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btn_CapNhat = new com.Product.swing.ButtonBadges();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Sửa Sản Phẩm");

        txt_MaSanPham.setEnabled(false);
        txt_MaSanPham.setLabelText("Mã Sản Phẩm");

        txt_TenSanPham.setLabelText("Tên Sản Phẩm");

        txt_MoTaSanPham.setColumns(20);
        txt_MoTaSanPham.setRows(5);
        jScrollPane2.setViewportView(txt_MoTaSanPham);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mô tả sản phẩm");

        btn_CapNhat.setBackground(new java.awt.Color(255, 204, 204));
        btn_CapNhat.setText("Cập Nhật");
        btn_CapNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_MaSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_TenSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_MaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_TenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        // TODO add your handling code here:

        SanPham newSanPham = getFormData();

        if (newSanPham == null) {
            return;
        }

// Hiển thị hộp thoại xác nhận
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn cập nhật sản phẩm này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (repo.update(newSanPham, id_sp)) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công!!!");
                this.dispose(); // Đóng cửa sổ hiện tại
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại!!!");
                this.dispose(); // Đóng cửa sổ hiện tại
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cập nhật đã bị hủy");
            this.dispose(); // Đóng cửa sổ hiện tại nếu người dùng chọn NO
        }

    }//GEN-LAST:event_btn_CapNhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaSanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaSanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaSanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaSanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaSanPhamJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.Product.swing.ButtonBadges btn_CapNhat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.Product.GUI.textfield.TextField txt_MaSanPham;
    private javax.swing.JTextArea txt_MoTaSanPham;
    private com.Product.GUI.textfield.TextField txt_TenSanPham;
    // End of variables declaration//GEN-END:variables
}
